### ISSUE TITLE
Texture distribution

### ISSUE THREAD

**Issue by photopea** [BinomialLLC/crunch#15]
Hi. I would like to show you my tool www.Photopea.com . You can use it as a viewer of .DDS files (works even on your phone). It supports BC1, BC2, BC3 and BC7 (DX10) compressions.

I also have a question about the strategy of the texture distribution. I am new to this area.

First, we want textures to be small "on the wire" (on a DVD / HDD / delivered over the internet). Next, we want them to be small in the GPU memory. I think it is clear, that any non-GPU-ish lossy compression (such as JPG or WebP) can achieve much better quality/size ratio, than any DXTx format (even zipped DXTx). So JPG or WebP is more suiteble for using "on the wire".

I often see developers directly distributing textues in DXTx format (DDS files) "on the wire". The usual excuse is, that decoding JPG and encoding it into DXTx (at the moment of using the texture) would be too time-consuming (while DXTx can be copied to the GPU without any modifications).

I implemented a very naive DXT1 compression into Photopea (File - Export - DDS) and it is surprisingly fast (1 MPx texture takes 80 ms to encode). So I feel like compressing textures (to DXTx) right before sending them to the GPU makes sense. So what is the purpose of the DDS format? Why do developers distribute textures in the DDS "on the wire", when there are better compression methods?

**Comment by richgel999** [comment]
Hi - Developers usually offline compress to DXT1/BC1 using non-realtime encoders, to get every last bit of quality. Real-time encoders are fast but lose quality. On some AAA titles, developers use BC1 for nearly everything (including normal maps!), so they need all the quality they can get.
Regards,
-Rich
