### ISSUE TITLE
Please consider CC0 license instead

### ISSUE THREAD

**Issue by neilk** [BinomialLLC/crunch#35]
Hi! Some colleagues of mine work on VR gaming, and they were excited that you chose to dedicate this work to the public domain. Thank you!

I'm a license nerd, since I worked for years on getting Wikipedia's image database properly licensed. Unfortunately, the status of "public domain dedications" is a bit fuzzy. It _might_ hold in the USA and EU, but worldwide, there's no such standard. Even at small companies and non-profits, there are legal departments that have to be careful about these matters.

It's true, Public Domain declarations are relatively low risk. But if you want to give the worldwide community maximum rights in a legally tested way, the current best option is to use the [Creative Commons Zero](https://creativecommons.org/share-your-work/public-domain/cc0/) license.

**Comment by richgel999** [comment]
Thanks for the feedback. I explicitly wanted the software to be placed into the Public Domain in the United States, and my attorneys in two states said that was acceptable. We looked at the Creative Commons Zero license, but it doesn't place the work explicitly into the Public Domain (it doesn't have mention "public domain") so it wasn't usable.

Also, if the fallback clauses/waivers don't apply, then the unlicense (which is very popular) is going to be in trouble too, so I'm not too worried. If a company has issues with either Public Domain and/or the fallback license they can contact me directly.
